# Generated by Django 4.0.2 on 2022-02-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrivalCity',
            field=models.CharField(max_length=10),
        ),
    ]
